#%RAML 1.0
---
title: Contract Information API for CustomerPortal
version: 2.0.1
baseUri: http://localhost:8080/v2

##
## version 2 API Definitions
##

types:
  EndUser:
    type: number
    default: 1
  SoldToParty:
    type: number
    default: 2
  Account:
    type: number
    default: 3
  Reseller:
    type: number
    default: 7
  Sales:
    type: number
    default: 9
  AccountType: [ EndUser | SoldToParty | Account | Reseller | Sales ]
#
#
/contracts:
  displayName: Contrancts Data
  get:
    description: Contracnts data
#      headers:
#        Date:
#          type: datetime
#          format: rfc2616
#          required: true
#        User-Agent:
#          type: string
#          required: true
    queryParameters:
      accountid:
        type: string
        required: true
      accounttype:
        type: AccountType
      requester:
        type: string
        required: true
      startDate:
        type: datetime
        format: rfc2616
        required: false
      endDate:
        type: datetime
        format: rfc2616
        required: false
      page:
        type: number
        format: int64
        required: true
      per_page:
        type: number
        format: int
        required: true
    responses:
      200:
        headers:
          Link:
            required: false
          X-Total-Count:
            required: false
        body:
          application/json:
      400:
        description: Invalid query supplied.
        body:
          application/json:
            example: |
              {
                "code": 400,
                "status": "error",
                "message": "Invalid query supplied."
              }
      404:
        description: There are no Contract Data.
        body:
          application/json:
            example: |
              {
                "code": 404,
                "status": "error",
                "message": "There are no Contract Data."
              }
  /{contractid}:
    displayName: Contract by ContractID
    uriParameters:
      contractid:
        description: |
          Contract Data that identifies the ContractID(10 digit).
        type: string
        example: "/0005188306"
        required: true
    get:
      description: Contrancts data filtered by CompanyID.
      queryParameters:
        requester:
          type: string
          required: true
      responses:
        200:
          body:
            application/json:
        400:
          description: Invalid query supplied.
          body:
            application/json:
              example: |
                {
                  "code": 400,
                  "status": "error",
                  "message": "Invalid query supplied."
                }
        404:
          description: There are no Contranct Data.
          body:
            application/json:
              example: |
                {
                  "code": 404,
                  "status": "error",
                  "message": "There are no Contract Data."
                }
  /equipments/{ibibase}:
    description:
    uriParameters:
      ibibase:
        description: 設置ベース（Zibibase）例：000000000000237210
        type: string
        required: true
#          example: ??????(18-digit code ?)
    get:
      description:
      queryParameters:
        requester:
          type: string
          required: true
        page:
          type: number
          format: int64
          required: true
        per_page:
          type: number
          format: int
          required: true
      responses:
        200:
          headers:
            Link:
              required: false
            X-Total-Count:
              required: false
          body:
            application/json:
        400:
          description: Invalid query supplied.
          body:
            application/json:
              example: |
                {
                  "code": 400,
                  "status": "error",
                  "message": "Invalid query supplied."
                }
        404:
          description: There are no Contranct Data.
          body:
            application/json:
              example: |
                {
                  "code": 404,
                  "status": "error",
                  "message": "There are no Contract Data."
                }
#
#
/companies/{companyid}:
  description:
  uriParameters:
    companyid:
      description: 会社コード
      type: string
      required: true
  get:
    description: Get company data
    queryParameters:
      requester:
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
#                example: |
#                  {
#                    "status": 200,
#                    "data": {
#                        "d": {
#                            "name1": "Company Name"
#                          }
#                      }
#                  }
      400:
        description: Invalid query supplied.
        body:
          application/json:
            example: |
              {
                "code": 400,
                "status": "error",
                "message": "Invalid query supplied."
              }
      404:
        description: There are no Company Data.
        body:
          application/json:
            example: |
              {
                "code": 404,
                "status": "error",
                "message": "There are no Contract Data."
              }
