#%RAML 0.8
---
title: Customer Portal API
version: 0.3
baseUri: http://localhost:8080/v1

/v1:
  /contracts:
    displayName: Contracts
    #description: |
    # A ...
    get:
      description: Contract information from Fiori(SAP/HANA)
      queryParameters:
        companyId:
          description: |
            Filter parameter of company Name.
          type: string
          required: true
          #example: 株式会社はまなすｲﾝﾌｫﾒｰｼｮﾝ
        requester:
          description: |
            Filter parameter of requester's email address.
          type: string
          required: false
          example: nob@hicom.com
        startDate:
          description: |
            Filter parameter of start date. defined in RFC2616 and GMT. HTTP will use UTC, becareful
          type: date
          required: false
          example: Sun, 06 Nov 1994 08:49:37 GMT
        endDate:
          description: |
            Filter parameter of start date. defined in RFC2616 and GMT. HTTP will use UTC, becareful
          type: date
          required: false
          example: Sun, 06 Nov 1994 08:49:37 GMT
        searchLimit:
          description: |
            Filter parameter of search row max. max value is 500 and default value is 20.
          type: number
          minimum: 5
          required: true
          example: 20
      responses:
        200:
          body:
            application/json:
              example: |
                  {
                    "d": {
                      "results": [
                        {
                          "__metadata": {
                            "id": "http://nwgw.netone.co.jp:80/sap/opu/odata/sap/Z0001_CONTRACT_EQUIPMENT_INFO_SRV/SEARCH_CONTINFOSet(ZcntrctNo='',Zconid='0005188306')",
                            "uri": "http://nwgw.netone.co.jp:80/sap/opu/odata/sap/Z0001_CONTRACT_EQUIPMENT_INFO_SRV/SEARCH_CONTINFOSet(ZcntrctNo='',Zconid='0005188306')",
                            "type": "Z0001_CONTRACT_EQUIPMENT_INFO_SRV.SEARCH_CONTINFO"
                          },
                          "ZcontStartDateLow": "",
                          "ZcntrctNo": "",
                          "ZcontStartDateHigh": "",
                          "Zconid": "0005188306",
                          "ZcontEndDateLow": "",
                          "ZcontStartDate": "2016/11/01",
                          "ZcontEndDateHigh": "",
                          "ZcontEndDate": "2017/10/31",
                          "ZcontText": "10月満了保守更新（バンドル版）",
                          "ZcontorsName": "株式会社エクシード",
                          "Zuser": "株式会社エクシード",
                          "ZcallerName": "",
                          "ZsalesReptive": "加賀谷 誠 (ZZ00002140)",
                          "ZtechReptive": "",
                          "ZcustContNo": "O-030-16-161001",
                          "ZserialNo": "",
                          "Zoverflg": "",
                          "Zurl": "/sap/bc/ui5_ui5/ui2/ushell/shells/abap/FioriLaunchpad.html?sap-client=500&sap-language=JA#Z0001_INSTRACT_INST-Search_Instract&/contract/0005188306"
                        }
                      ]
                    }
                  }
        400:
          description: Invalid query supplied.
        404:
          description: There are no contract data.
  
    /{contractId}:
      displayName: Contract filtered by ContractID (ZcntrctNo)
      #description: |
      # A ...
      uriParameters:
        contractId:
          description: |
            Contract ID is ZcntrctNo　（個別契約番号）
          type: string
          example: SC12013301-00
      get:
        description: Contract information filtered by contractId(ZcntrctNo).
        responses:
          200:
            body:
              application/json:
                example: |
                    {
                      "d": {
                        "__metadata": {
                          "id": "http://nwgw.netone.co.jp:80/sap/opu/odata/sap/Z0001_CONTRACT_EQUIPMENT_INFO_SRV/CONT_OVERVIEWSet('%20%20%205188306')",
                          "uri": "http://nwgw.netone.co.jp:80/sap/opu/odata/sap/Z0001_CONTRACT_EQUIPMENT_INFO_SRV/CONT_OVERVIEWSet('%20%20%205188306')",
                          "type": "Z0001_CONTRACT_EQUIPMENT_INFO_SRV.CONT_OVERVIEW"
                        },
                        "ZcontType": "保守",
                        "Zurl": "http://sv-crmprdg208.netone.co.jp:8000/sap/bc/gui/sap/its/webgui?sap-client=500&~TRANSACTION=ZCR0042 P_LIMITS=999999&S_CNTRCT-LOW=   5188306&~OKCODE=ONLI",
                        "ZcontNo": "D509008",
                        "ZcntrctNo": "",
                        "Zguid": "0050568E-30C7-1EE6-A7E6-8D5FDF849E5D",
                        "Zconid": "   5188306",
                        "ZibIbase": "000000000000237210",
                        "Ztext": "10月満了保守更新（バンドル版）",
                        "ZdeliDest": "株式会社エクシード",
                        "ZcustReptive": "鈴木",
                        "ZcallCompName": "",
                        "ZnhCallerInfo": "株式会社エクシード　　東京都港区高輪3-7-16　　苙口　裕介　03-6422-0026　",
                        "ZsalesReptive": "加賀谷 誠 (ZZ00002140)",
                        "ZtechReptive": "",
                        "ZcustContNo": "O-030-16-161001",
                        "Zstatus": "30 リリース",
                        "ZofferedPrice": "0 JPY",
                        "ZupdateFlg": "なし",
                        "ZcontStartDate": "2016/11/01",
                        "ZcontEndDate": "2017/10/31",
                        "ZexecuteDate": "2016/10/27",
                        "ZcontFixDate": "",
                        "Zeolmainte": "",
                        "ZconstDiv": "",
                        "ZsalesOrg": "1000"
                      }
                    }                
          400:
            description: Invalid query supplied.
          404:
            description: There are no contract data.
  
  
  /companies:
    displayName: Companies
    #description: |
    #  A collection of teams that are participating in La Liga. Teams API allow you add, remove and retrieve individual team information from La Liga.
    get:
      description: Companies information from SAP/HANA
      queryParameters:
        companyName:
          description: |
            Filter the list of companies by company's ID (uniq company-code or customer's code?).
          type: string
          required: false
          example: CPY2001
        email:
          description: |
            Filter the list of companies by company's ID (uniq company-code or customer's code?).
          type: string
          required: false
          example: unigrav@gmail.com
        searchLimit:
          description: |
            Filter parameter of search row max. max value is 500 and default value is 20.
          type: number
          minimum: 5
          required: true
          example: 20
      responses:
        200:
          body:
            application/json:
            #schema: !include schemas/companies-schema-input.json
            #example: !include examples/companies.json
              example: |
                  {
                  "d": {
                    "__metadata": {
                      "id": "http://nwgw.netone.co.jp:80/sap/opu/odata/sap/crm_opportunity/AccountCollection('105585')",
                      "uri": "http://nwgw.netone.co.jp:80/sap/opu/odata/sap/crm_opportunity/AccountCollection('105585')",
                      "type": "CRM_OPPORTUNITY.Account",
                      "etag": "W/\"'1388C1A4ECB9F234EF28885531AA853465C5D9FF'\""
                        },
                      "name1": "株式会社エクシード"
                      }
                    }
        400:
          description: Invalid query supplied.
        404:
          description: There are no company data.
  
    /{companyId}:
      displayName: Company by CompanyId
      #description: |
        # A ....
      uriParameters:
        companyId:
          description: |
            Company code that identifies the Company.
          type: string
          example: CPY2001
      get:
        description: Company information filtered by companyId.
        responses:
          200:
            body:
              application/json:
              #example: !include examples/companies.json
          400:
            description: Invalid query supplied.
          404:
            description: There are no company data.
#
#
/v2:
  /companies:
    /{companyid}:
      description:  v2 not support. 
      uriParameters:
        companyid:
          description: Company Code
          type: string
          required: true
      get:
        queryParameters:
          requester:
            type: string
            required: true
        responses:
          200:
            body:
              application/json:
          400:
            body:
              application/json:
          404:
            body:
              application/json:  
  /contracts:
    get:
      description: get Contracts List
      queryParameters:
        accounttype:
          type: number
          required: true
        accountid:
          type: string
          required: true
        requester:
          type: string
          required: true
        startDate:
          type: string
          required: false
        endDate:
          type: string
          required: false
        page:
          type: number
          required: true
        per_page:
          type: number
          required: true
      responses:
        200:
          headers:
            Link:
              required: false
            X-Total-Count:
              required: false
          body:
            application/json:
        400:
          body:
            application/json:
        404:
          body:
            application/json:                 
    /{contractid}:
      uriParameters:
        contractid:
          type: string
          required: true
          example: "0000012345"
      get:
        queryParameters:
          requester:
            type: string
            required: true
        responses:
          200: 
            body:
              application/json:
          400:
            body:
              application/json:
          404:
            body:
              application/json:
    /equipments:
      /{ibibase}:
        uriParameters:
          ibibase:
            type: string
            required: true
            description: 設置ベース(Zibibase)による保守対象機器リストの取得
        get:
          queryParameters:
            requester:
              type: string
              required: true
            page:
              type: number
              required: true
            per_page:
              type: number
              required: true
          responses:
            200: 
              headers:
                Link:
                  required: false
                X-Total-Count:
                  required: false
              body:
                application/json:
            400:
              body:
                application/json:
                  example: |
                        {
                          "code": 400,
                          "status": "Error",
                          "message": "Invalid query supplied."
                        }
            404:
              body:
                application/json:
                            
  
