swagger: '2.0'
info:
  version: 2.0.1
  title: OpenAPI v2.0
  description: description
  termsOfService: terms
#  contact:
#    name: OpenAPI Support Staff
#    url: https://apigw.unigrav-one/contact
#    email: support-openapi@unigrav-one
#  license:
#    name: ???
#    url: ???
#host: apigw.unigrav-one
basePath: /v2
schemes:
  - https
paths:
  /contracts:
    get:
      description: |
        Get contract data. The search key are accounttype and accountid.  
        保守契約の基本情報を提供する。対象となる保守契約は、指定したaccountid（契約コード：会社コード）が主契約となっている保守契約情報が提供される。accounttype（アカウント種別）を2（  
        以下のパラメータは、API基盤利用時のアクセスログとして記録され一定の期間保存される。アクセスログは、関連サービスの障害解析、関連サービスの品質向上のデータとして利用される他、不正アクセス等による関連サービスの停止時の解析等にも利用される。ログデータの利用については、サービス規約およびサポートページを参照すること
      parameters:
      - name: "accounttype"
        in: "query"
        type: "integer"
        format: "int32"
        required: true
        default: 2
        description: |
          AccountTypeとして、2（ZsoidToParty：受注先ID）のみが指定可能（May 2017）将来的な拡張として、Zaccount（1：アカウントID）、Zenduser（3：エンドユーザID)が予約されている。
      - name: "accountid"
        in: "query"
        type: "string"
        required: true
        description: |
          保守契約情報の検索キーとしてAccountIDを指定する。現在は10桁の受注先IDを指定する「\d{10}」将来的には、AccountTypeが拡張され、指定したアカウント種別により適切なIDを設定する
      - name: "requester"
        in: "query"
        type: "string"
        required: true
        description: |
          本APIをコールするエンドユーザのアカウントIDを設定する。現在は、利用者として登録されているEmailアドレスを指定する必要がある。
      - name: "startDate"
        in: "query"
        type: "string"
        required: false
        default: "2016/04/01"
      - name: "endDate"
        in: "query"
        type: "string"
        required: false
      - name: "page"
        in: "query"
        type: "integer"
        format: "int64"
        minimum: 1
        required: true
        default: 1
      - name: "per_page"
        in: "query"
        type: "integer"
        format: "int64"
        minimum: 1
        maximum: 100
        required: true
        default: 10
      responses:
        '200':
          description: "OK"
          headers:
            X-Total-Count:
              type: "integer"
              format: "int64"
          schema:
            type: "object"
            properties:
              d:
                type: "object"
                properties:
                  code:
                    type: "string"
                    example: "200"
                  message:
                    type: "string"
                    example: "Success"
                  results:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        ZcntrctNo:
                          type: "string"
                          example: "0000012345"
                        ZcontStartDateLow:
                          type: "string"
                          example: "2015/04/01"
        '400':
          description: "ERROR"
        '404':
          description: "ERROR"
  '/contracts/{contractid}':
    get:
      parameters:
      - name: "contractid"
        in: "path"
        type: "string"
        required: true
      responses:
        200:
          description: OK
   
